FROM golang:1.22

WORKDIR /app

RUN go env -w GOPROXY="https://goproxy.cn,direct"

COPY . .

RUN go mod download

RUN go build -ldflags '-s -w' -o /gproxy ./cmd/gproxy

# we can run container with `-e GPROXY_CONFIG="SOME 
# MULTI
# LINE 
# CONFIG" gproxy`

CMD ["/gproxy"]